BEGIN TRANSACTION;
CREATE TABLE biotrackthc_undo_history (
    id bigint NOT NULL,
    sessiontime bigint,
    action text,
    orgid bigint,
    barcode text,
    transactionid bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_tax_obligation_reports (
    id bigint NOT NULL,
    orgid bigint,
    location bigint,
    month smallint,
    year integer,
    time_start bigint,
    time_end bigint,
    gross_sales numeric,
    excise_tax numeric,
    amount_due numeric,
    locked smallint DEFAULT 1,
    deleted smallint DEFAULT 0,
    unlock_time bigint,
    submit_time bigint,
    re_submit_time bigint,
    transactionid bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_plantslog (
    id bigint NOT NULL,
    plantid text,
    strain text,
    sessiontime bigint,
    transactionid bigint,
    seed smallint DEFAULT 0,
    inventoryid text,
    parentid text,
    deleted smallint DEFAULT 0,
    deletetime bigint,
    location bigint DEFAULT 1,
    state smallint DEFAULT 0,
    cloneconverted smallint DEFAULT 0,
    seized smallint,
    orgid bigint DEFAULT 1,
    harvestscheduled smallint,
    harvestscheduletime bigint,
    created timestamp,
    harvestcollect smallint,
    curecollect smallint,
    room bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_plants (
    id text NOT NULL,
    strain text,
    sessiontime bigint,
    transactionid bigint,
    seed smallint DEFAULT 0,
    parentid text,
    deleted smallint DEFAULT 0,
    deletetime bigint,
    location bigint DEFAULT 1,
    state smallint DEFAULT 0,
    cloneconverted smallint DEFAULT 0,
    seized smallint,
    orgid bigint DEFAULT 1,
    harvestscheduled smallint,
    harvestscheduletime bigint,
    harvestcollect smallint,
    curecollect smallint,
    room bigint,
    mother smallint DEFAULT 0,
    removescheduled smallint DEFAULT 0,
    removescheduletime bigint,
    removereason text,
    idserial bigint NOT NULL,
    modified timestamp,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_plantderivatives (
    id bigint NOT NULL,
    plantid text,
    sessiontime bigint,
    transactionid bigint,
    deleted smallint DEFAULT 0,
    created timestamp,
    inventorytype smallint,
    dweight numeric,
    daccountedfor smallint,
    inventoryid text,
    dwholeweight numeric,
    orgid bigint,
    location bigint,
    droom bigint,
    addlcollections smallint DEFAULT 0,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_organizations_labs (
    orgid bigint NOT NULL,
    orgname text,
    orgactive smallint DEFAULT 1,
    orglicense text,
    orgstatus smallint DEFAULT 2
);
CREATE TABLE biotrackthc_organizations (
    orgname text,
    orgid bigint NOT NULL,
    orgactive smallint DEFAULT 1,
    orglicense text,
    fifteendaystart bigint,
    orgstatus smallint DEFAULT 2
);
CREATE TABLE biotrackthc_locations_labs (
    id bigint NOT NULL,
    orgid bigint,
    locationid bigint NOT NULL,
    name text,
    address1 text,
    address2 text,
    city text,
    state text,
    zip text,
    website text,
    deleted smallint DEFAULT 0,
    locationtype smallint DEFAULT 0,
    licensenum text,
    fax text,
    mip smallint DEFAULT 0,
    medical smallint DEFAULT 1,
    locationexp bigint,
    locationissue bigint,
    status text,
    districtcode text,
    loclatitude numeric,
    loclongitude numeric,
    mailaddress1 text,
    mailaddress2 text,
    mailcity text,
    mailstate text,
    mailzip text,
    locubi text,
    producer smallint DEFAULT 0,
    processor smallint DEFAULT 0,
    retail smallint DEFAULT 0,
    transactionid bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_locations (
    orgid bigint,
    locationid bigint NOT NULL,
    name text,
    address1 text,
    address2 text,
    city text,
    state text,
    zip text,
    deleted smallint DEFAULT 0,
    locationtype smallint DEFAULT 0,
    licensenum text,
    id bigint NOT NULL,
    locationexp bigint,
    locationissue bigint,
    status text,
    districtcode text,
    loclatitude numeric,
    loclongitude numeric,
    mailaddress1 text,
    mailaddress2 text,
    mailcity text,
    mailstate text,
    mailzip text,
    locubi text,
    producer smallint DEFAULT 0,
    processor smallint DEFAULT 0,
    retail smallint DEFAULT 0,
    transactionid bigint,
    transactionid_original bigint,
    fifteenday_end bigint,
    delete_time bigint
);
CREATE TABLE biotrackthc_labresults_solvent_screening (
    id bigint NOT NULL,
    sample_id bigint,
    name text,
    value numeric,
    failure smallint DEFAULT 0,
    location bigint,
    orgid bigint,
    lab_provided smallint DEFAULT 0
);
CREATE TABLE biotrackthc_labresults_samples (
    id bigint NOT NULL,
    inventoryid text,
    quantity numeric,
    sessiontime bigint,
    inventorytype bigint,
    strain text,
    product_name text,
    deleted smallint DEFAULT 0,
    result smallint DEFAULT 0,
    lab_license text,
    sample_use smallint,
    location bigint,
    orgid bigint,
    transactionid bigint,
    parentid text,
    received smallint DEFAULT 0,
    received_quantity numeric,
    transactionid_original bigint,
    sample_amount_used numeric,
    sample_amount_destroyed numeric,
    sample_amount_other numeric,
    other_sample_id text,
    inventoryparentid text 
);
CREATE TABLE biotrackthc_labresults_potency_analysis (
id bigint NOT NULL,
sample_id bigint,
name text,
value numeric,
units smallint,
failure smallint DEFAULT 0,
location bigint,
orgid bigint,
lab_provided smallint DEFAULT 0
);
CREATE TABLE biotrackthc_labresults_moisture_content (
id bigint NOT NULL,
sample_id bigint,
name text,
value numeric,
failure smallint DEFAULT 0,
location bigint,
orgid bigint,
lab_provided smallint DEFAULT 0
);
CREATE TABLE biotrackthc_labresults_micro_screening (
id bigint NOT NULL,
sample_id bigint,
name text,
value numeric,
failure smallint DEFAULT 0,
location bigint,
orgid bigint,
lab_provided smallint DEFAULT 0
);
CREATE TABLE biotrackthc_labresults_foreign_matter (
id bigint NOT NULL,
sample_id bigint,
name text,
value numeric,
failure smallint DEFAULT 0,
location bigint,
orgid bigint,
lab_provided smallint DEFAULT 0
);
CREATE TABLE biotrackthc_inventorytransfers (
    id bigint NOT NULL,
    inventoryid text,
    strain text,
    weight numeric DEFAULT 0,
    transactionid bigint,
    location bigint DEFAULT 1,
    direction smallint DEFAULT 0,
    requiresweighing smallint DEFAULT 1,
    transfertype smallint DEFAULT 0,
    orgid bigint,
    parentid text,
    inventorytype smallint DEFAULT (-1),
    usableweight numeric,
    outbound_license text,
    inbound_license text,
    description text,
    saleprice text,
    manifestid text,
    manifest_stop text,
    received smallint DEFAULT 0,
    receiveweight numeric,
    deleted smallint DEFAULT 0,
    unitprice numeric,
    is_refund smallint,
    refund_amount numeric,
    inbound_location bigint,
    transactionid_original bigint,
    inbound_orgid bigint,
    transactionid_original_inbound bigint
);
CREATE TABLE biotrackthc_inventorysamples (
    id bigint NOT NULL,
    orgid bigint,
    sample_type smallint,
    vendor_id text,
    inventoryid text,
    quantity numeric,
    sessiontime bigint,
    transactionid bigint,
    location bigint,
    transactionid_original bigint,
    deleted smallint DEFAULT 0
);
CREATE TABLE biotrackthc_inventoryrooms (
    id bigint NOT NULL,
    orgid bigint,
    location bigint,
    roomid bigint,
    name text,
    deleted smallint DEFAULT 0,
    quarantine smallint DEFAULT 0,
    transactionid bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_inventorylog (
    logid bigint NOT NULL,
    id text,
    sessiontime bigint,
    strain text,
    weight numeric DEFAULT 0,
    transactionid bigint,
    plantid text,
    location bigint DEFAULT 1,
    remainingweight numeric DEFAULT 0,
    requiresweighing smallint DEFAULT 1,
    parentid text,
    inventorytype smallint DEFAULT (-1),
    wet smallint DEFAULT 0,
    seized smallint,
    orgid bigint DEFAULT 1,
    deleted smallint DEFAULT 0,
    created timestamp,
    plantarray text,
    usableweight numeric,
    iaction smallint,
    lasttime bigint,
    inventoryparentid text,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_inventoryconversions (
    id bigint NOT NULL,
    inventoryid text,
    oldweight numeric DEFAULT 0,
    newweight numeric DEFAULT 0,
    difference numeric DEFAULT 0,
    sessiontime bigint,
    transactionid bigint,
    childid text,
    childweight numeric,
    requiresweighing smallint DEFAULT 1,
    orgid bigint DEFAULT 1,
    inventoryarray text,
    inventorytype smallint,
    location bigint,
    transactionid_original bigint,
    inventorytype_parent smallint,
    parentweight_start numeric,
    parentweight_end numeric,
    parent_difference numeric,
    child_usableweight numeric
);
CREATE TABLE biotrackthc_inventorycombinations (
    id bigint NOT NULL,
    newid text,
    oldid text,
    sessiontime bigint,
    transactionid bigint,
    newtype smallint,
    oldtype smallint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_inventoryadjustments (
    id bigint NOT NULL,
    inventoryid text,
    oldweight numeric DEFAULT 0,
    newweight numeric DEFAULT 0,
    difference numeric DEFAULT 0,
    sessiontime bigint,
    transactionid bigint,
    orgid bigint DEFAULT 1,
    reason text,
    atype smallint,
    location bigint,
    transactionid_original bigint,
    inventory_time bigint
);
CREATE TABLE biotrackthc_inventory_statistics (
    id bigint NOT NULL,
    orgid bigint,
    location bigint,
    inventorytype smallint,
    quantity numeric DEFAULT 0,
    created timestamp,
    day bigint
);
CREATE TABLE biotrackthc_inventory_qa_fail_exempt (
    id bigint NOT NULL,
    inventoryid text,
    sessiontime bigint,
    orgid bigint,
    deleted smallint DEFAULT 0
);
CREATE TABLE biotrackthc_inventory_fifteen (
    id bigint NOT NULL,
    inventoryid text,
    orgid bigint,
    location bigint,
    deleted smallint DEFAULT 0,
    sessiontime bigint,
    quantity numeric,
    inventorytype smallint,
    strain text
);
CREATE TABLE biotrackthc_inventory (
    id text,
    sessiontime bigint,
    strain text,
    weight numeric DEFAULT 0,
    transactionid bigint,
    plantid text,
    location bigint DEFAULT 1,
    remainingweight numeric DEFAULT 0,
    requiresweighing smallint DEFAULT 1,
    parentid text,
    inventorytype smallint DEFAULT (-1),
    wet smallint DEFAULT 0,
    seized smallint,
    orgid bigint DEFAULT 1,
    deleted smallint DEFAULT 0,
    plantarray text,
    usableweight numeric,
    removescheduled smallint DEFAULT 0,
    removescheduletime bigint,
    inventoryparentid text,
    productname text,
    currentroom bigint,
    idserial bigint NOT NULL,
    removereason text,
    inventorystatus smallint,
    inventorystatustime bigint,
    inventoryparentidpct text,
    sample_id text,
    source_id text,
    transactionid_original bigint,
    recalled smallint
);
CREATE TABLE biotrackthc_growrooms (
    id bigint NOT NULL,
    orgid bigint,
    location bigint,
    roomid bigint,
    name text,
    deleted smallint DEFAULT 0,
    transactionid bigint,
    transactionid_original bigint
);
CREATE TABLE biotrackthc_dispensing (
    id bigint NOT NULL,
    orgid bigint,
    weight numeric DEFAULT 0,
    sessiontime bigint,
    inventoryid text,
    transactionid bigint,
    location bigint DEFAULT 1,
    price numeric,
    usableweight numeric,
    itemnumber integer,
    deleted smallint DEFAULT 0,
    refunded smallint,
    transactionid_original bigint,
    inventorytype smallint,
    created timestamp,
    terminal_id text
);
COMMIT;
